# Generated by Django 4.1.1 on 2022-09-21 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Distrito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_dpto", models.CharField(max_length=2, verbose_name="cod_dpto")),
                ("cod_dist", models.CharField(max_length=2, verbose_name="cod_dist")),
                (
                    "desc_dist",
                    models.CharField(max_length=200, verbose_name="desc_dist"),
                ),
                ("ubigeo", models.CharField(max_length=6, verbose_name="ubigeo")),
            ],
            options={"verbose_name": "distrito", "verbose_name_plural": "distritos",},
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_dpto", models.CharField(max_length=2, verbose_name="cod_dpto")),
                ("cod_prov", models.CharField(max_length=2, verbose_name="cod_prov")),
                (
                    "desc_prov",
                    models.CharField(max_length=200, verbose_name="desc_prov"),
                ),
                ("cod", models.CharField(max_length=4, verbose_name="cod")),
            ],
            options={"verbose_name": "provincia", "verbose_name_plural": "provincias",},
        ),
        migrations.CreateModel(
            name="Gestante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="telefono"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("0", ""), ("man", "homem"), ("woman", "mulher")],
                        default="0",
                        max_length=5,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "distrito",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GestanteApp.distrito",
                        verbose_name="Distrito",
                    ),
                ),
            ],
            options={"verbose_name": "Gestante", "verbose_name_plural": "Gestantes",},
        ),
        migrations.AddField(
            model_name="distrito",
            name="cod_prov",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="GestanteApp.provincia",
                verbose_name="provincia",
            ),
        ),
    ]
