# Generated by Django 4.1.1 on 2022-09-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GestanteApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gestante",
            options={"verbose_name": "gestante", "verbose_name_plural": "gestantes"},
        ),
        migrations.AddField(
            model_name="gestante",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GestanteApp.provincia",
                verbose_name="provincia",
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="distrito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="GestanteApp.distrito",
                verbose_name="distrito",
            ),
        ),
    ]
