# Generated by Django 4.1.1 on 2022-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestanteApp", "0002_alter_gestante_options_gestante_provincia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestante",
            name="atendido",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="atendido"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="control",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="control"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="examen",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="examen"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="sulfato",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="sulfato"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="tamizaje",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="tamizaje"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="violencia",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="violencia"
            ),
        ),
    ]
