# Generated by Django 4.1.1 on 2022-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GestanteApp", "0004_gestante_paquete_gestante_por_atendido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestante",
            name="captacion",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="captacion"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="meta_captacion",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="meta_captacion"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="meta_paquete",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="meta_paquete"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="meta_violencia",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="meta_violencia"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_captacion",
            field=models.IntegerField(
                blank=True, max_length=100, null=True, verbose_name="por_captacion"
            ),
        ),
    ]
