# Generated by Django 4.1.1 on 2022-09-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "GestanteApp",
            "0006_rename_meta_violencia_gestante_meta_int_violencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gestante",
            name="cred_nino",
            field=models.IntegerField(blank=True, null=True, verbose_name="cred_nino"),
        ),
        migrations.AddField(
            model_name="gestante",
            name="dni_nino",
            field=models.IntegerField(blank=True, null=True, verbose_name="dni_nino"),
        ),
        migrations.AddField(
            model_name="gestante",
            name="hemoglobina",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="hemoglobina"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="meta_paquete_nino",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="meta_paquete_nino"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="paquete_nino",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="paquete_nino"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_cred_nino",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_cred_nino"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_dni_nino",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_dni_nino"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_hemoglobina",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_hemoglobina"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_paquete_nino",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_paquete_nino"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_suplementacion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_suplementacion"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="por_vacunas",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_vacunas"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="suplementacion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="suplementacion"
            ),
        ),
        migrations.AddField(
            model_name="gestante",
            name="vacunas",
            field=models.IntegerField(blank=True, null=True, verbose_name="vacunas"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="atendido",
            field=models.IntegerField(blank=True, null=True, verbose_name="atendido"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="captacion",
            field=models.IntegerField(blank=True, null=True, verbose_name="captacion"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="control",
            field=models.IntegerField(blank=True, null=True, verbose_name="control"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="examen",
            field=models.IntegerField(blank=True, null=True, verbose_name="examen"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="int_violencia",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="int_violencia"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="meta_captacion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="meta_captacion"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="meta_int_violencia",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="meta_violencia"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="meta_paquete",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="meta_paquete"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="paquete",
            field=models.IntegerField(blank=True, null=True, verbose_name="paquete"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_atendido",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_atendido"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_captacion",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_captacion"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_control",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_control"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_examen",
            field=models.IntegerField(blank=True, null=True, verbose_name="por_examen"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_int_violencia",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_int_violencia"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_paquete",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_paquete"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_sulfato",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_sulfato"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_tamizaje",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_tamizaje"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="por_violencia",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="por_violencia"
            ),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="sulfato",
            field=models.IntegerField(blank=True, null=True, verbose_name="sulfato"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="tamizaje",
            field=models.IntegerField(blank=True, null=True, verbose_name="tamizaje"),
        ),
        migrations.AlterField(
            model_name="gestante",
            name="violencia",
            field=models.IntegerField(blank=True, null=True, verbose_name="violencia"),
        ),
    ]
